name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.*

    - name: Restore dependencies
      run: dotnet restore webapi/webapi.csproj

    - name: Build
      run: dotnet build webapi/webapi.csproj --configuration Release
