name: Run tests on push

on:
  push:
    branches:
      - main
      - reactjs/dev
  pull_request:
    branches:
      - main
      - reactjs/dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0x

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests
      run: dotnet test --logger trx --results-directory TestResults

    - name: Commit changes if tests pass
      run: |
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes to commit"
        else
          git config --global user.name 'CI'
          git config --global user.email 'ci@example.com'
          git add .
          git commit -m "Tests passed [skip ci]"
          git push
        fi