name: Run tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Redis
      run: sudo apt update && sudo apt install redis-server -y

    - name: Start Redis server
      run: sudo systemctl start redis-server

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.*

    - name: Restore dependencies
      run: dotnet restore tests/tests.csproj

    - name: Run tests
      run: dotnet test --logger trx --results-directory TestResults
