name: Run tests and notify

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Redis
      run: sudo apt update && sudo apt install redis-server -y

    - name: Start Redis server
      run: sudo systemctl start redis-server

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.*

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests
      run: dotnet test --logger trx --results-directory TestResults

    - name: Commit changes if tests pass
      run: |
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes to commit"
        else
          git config --global user.name 'CI'
          git config --global user.email 'ci@example.com'
          git add .
          git commit -m "Tests passed [skip ci]"
          git push
        fi

    - name: Extract test results
      id: extract
      run: |
        echo "Extracting test results"
        error_messages=$(grep -oPm1 "(?<=<Message>)[^<]+" TestResults/*.trx | paste -sd "," -)
        stack_traces=$(grep -oPm1 "(?<=<StackTrace>)[^<]+" TestResults/*.trx | paste -sd "," -)
        result_line=$(dotnet test --logger "trx;LogFileName=test_results.trx" | grep "Passed!" | awk '{$1=$1};1')
        failed=$(echo "$result_line" | grep -oPm1 "(?<=Failed: )\d+")
        passed=$(echo "$result_line" | grep -oPm1 "(?<=Passed: )\d+")
        skipped=$(echo "$result_line" | grep -oPm1 "(?<=Skipped: )\d+")
        total=$(echo "$result_line" | grep -oPm1 "(?<=Total: )\d+")
        duration=$(echo "$result_line" | grep -oPm1 "(?<=Duration: )\S+")

        echo "::set-output name=failed::$failed"
        echo "::set-output name=passed::$passed"
        echo "::set-output name=skipped::$skipped"
        echo "::set-output name=total::$total"
        echo "::set-output name=duration::$duration"
        echo "::set-output name=error_messages::$error_messages"
        echo "::set-output name=stack_traces::$stack_traces"

    - name: Send Telegram Notification
      uses: appleboy/telegram-action@v0.1.0
      with:
        to: ${{ secrets.AIR_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN_BOT }}
        message: |
          Test results:
          - Status: ${{ job.status }}
          - Repository: ${{ github.repository }}
          - Branch: ${{ github.ref }}
          - Commit SHA: ${{ github.sha }}
          - User: ${{ github.actor }}
          - Total tests: ${{ steps.extract.outputs.total }}
          - Duration: ${{ steps.extract.outputs.duration }}
          - Passed tests: ${{ steps.extract.outputs.passed }}
          - Skipped tests: ${{ steps.extract.outputs.skipped }}
          - Failed tests: ${{ steps.extract.outputs.failed }}
          - Error messages: ${{ steps.extract.outputs.error_messages }}
          - Stack Trace : ${{ steps.extract.outputs.stack_traces }}
